

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Sincroniza tu código local con el contenedor
      - .:/app
      # Protege tus fotos para que se guarden en tu PC
      - ./media:/app/media
    # CRÍTICO: Le dice a Docker que lea tus variables de entorno
    env_file:
      - .env