# Generated by Django 6.0.6 on 2026-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'familia_de_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base_pesos', models.FloatField(blank=True, null=True)),
                ('stock_disponible', models.FloatField(blank=True, null=True)),
                ('eliminado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('razon_social', models.TextField(blank=True, null=True)),
                ('marca', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaProductoAgrupado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base_pesos', models.FloatField(blank=True, null=True)),
                ('stock_disponible', models.FloatField(blank=True, null=True)),
                ('eliminado', models.FloatField(blank=True, null=True)),
                ('descripcion_grupo', models.TextField()),
            ],
            options={
                'db_table': 'vista_producto_agrupado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
