# Generated by Django 6.0.6 on 2026-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base_pesos', models.FloatField(blank=True, null=True)),
                ('stock_disponible', models.FloatField(blank=True, null=True)),
                ('eliminado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('precio_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('modificacion_de_precios_id', models.IntegerField(blank=True, null=True)),
                ('receta', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('precio_antiguo_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'producto_precio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('razon_social', models.TextField(blank=True, null=True)),
                ('marca', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
