# Generated by Django 6.0.6 on 2026-08-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaProductoVariantes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('codigo_de_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descripcion_grupo', models.TextField(blank=True, null=True)),
                ('precio_base_pesos', models.FloatField(blank=True, null=True)),
                ('stock_disponible', models.FloatField(blank=True, null=True)),
                ('eliminado', models.FloatField(blank=True, null=True)),
                ('unidad_medida', models.TextField(blank=True, null=True)),
                ('familia_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('empaque_inner', models.CharField(blank=True, max_length=100, null=True)),
                ('empaque_master', models.CharField(blank=True, max_length=100, null=True)),
                ('empaque_pallet', models.CharField(blank=True, max_length=100, null=True)),
                ('indice_catalogo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_producto_variantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoGrupoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(db_index=True, unique=True)),
                ('grupo_personalizado', models.CharField(max_length=255)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo Manual de Producto',
                'verbose_name_plural': 'Grupos Manuales de Productos',
            },
        ),
    ]
