# Generated by Django 6.0.6 on 2026-06-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoPrecio',
        ),
    ]
