# Generated by Django 6.0.6 on 2026-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='catalogos/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prueba_catalogcache',
                'ordering': ['-version_number'],
                'managed': False,
            },
        ),
    ]
