# Generated by Django 6.0.6 on 2026-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
