# Generated by Django 6.0.6 on 2026-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_delete_productoprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'familia_de_productos',
                'managed': False,
            },
        ),
    ]
