# Generated by Django 6.0.6 on 2026-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_vistaproductovariantes_productogrupomanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogrupomanual',
            name='nombre_limpio_personalizado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
