# Generated by Django 6.0.6 on 2026-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_productogrupomanual_nombre_limpio_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='orden_grupo',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
