# Generated by Django 6.0.6 on 2026-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_imagenproducto_orden_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='¿Es Destacado / Oferta?'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='etiqueta_destacado',
            field=models.CharField(blank=True, default='OFERTA', max_length=50, null=True),
        ),
    ]
