# Generated by Django 6.0.6 on 2026-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_imagenproducto_es_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogrupomanual',
            name='subgrupo_personalizado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
