# Generated by Django 6.0.6 on 2026-09-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_productogrupomanual_subgrupo_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productogrupomanual',
            name='subgrupo_personalizado',
        ),
    ]
