# Generated by Django 6.0.6 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0007_remove_productogrupomanual_subgrupo_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogrupomanual',
            name='subgrupo_personalizado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
