# Generated by Django 6.0.6 on 2026-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0008_productogrupomanual_subgrupo_personalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('creados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
