# Generated by Django 6.0.6 on 2026-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0009_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='detalle_cambios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='detalle_errores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
