# Generated by Django 6.0.6 on 2026-09-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0010_synclog_detalle_cambios_synclog_detalle_errores'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='super_grupo',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Súper Grupo (agrupa varios grupos dentro de una familia)'),
        ),
    ]
