# Generated by Django 6.0.6 on 2026-09-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0011_imagenproducto_super_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruperFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_origen', models.CharField(db_index=True, max_length=50, unique=True)),
                ('url_ficha_tecnica', models.URLField(max_length=500)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha Técnica Truper (caché)',
                'verbose_name_plural': 'Fichas Técnicas Truper (caché)',
            },
        ),
    ]
